source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!


# Core
pod 'Liferay-iOS-SDK', '6.2.0.17'
pod 'Liferay-OAuth'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SMXMLDocument'
pod 'ODRefreshControl'

# Login & signup: save credentials
pod 'KeychainAccess'

