source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

inhibit_all_warnings!

target "WesterosEmployees-hybrid" do
    pod 'LiferayScreens', :path => '../../../..'

	pod 'TPKeyboardAvoiding'
	pod 'MGSwipeTableCell'
	pod 'PureLayout'
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
		end
	end
end
