source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target "WesterosBank" do
  pod 'LiferayScreens', :path => '../../../..'

  pod 'TPKeyboardAvoiding'
  pod 'MGSwipeTableCell'
end
