source 'https://github.com/CocoaPods/Specs.git'

pod 'MBProgressHUD', :git => 'https://github.com/jmnavarro/MBProgressHUD', :branch => 'cancel-delayed-hide'
pod 'SMXMLDocument'
pod 'UICKeyChainStore'
pod 'DTPickerPresenter'
pod 'TNRadioButtonGroup'
pod 'MDRadialProgress'
pod 'Liferay-iOS-SDK', :git => 'https://github.com/liferay/liferay-mobile-sdk.git'
