source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!


# Core
pod 'Liferay-iOS-SDK', '~> 7.0.3'
pod 'Liferay-OAuth', '~> 1.2.0'
pod 'MBProgressHUD', '0.9.1'
pod 'SMXMLDocument', '1.1'
pod 'ODRefreshControl', '1.2'
pod 'YapDatabase/SQLCipher', '2.8.2'

# Login & signup: save credentials
pod 'KeychainAccess', '2.3.1'

# UserPortrait
pod 'CryptoSwift', '0.1.1'

# DDLForm
pod 'DTPickerPresenter', '0.2.0'
pod 'TNRadioButtonGroup', '0.4'
pod 'MDRadialProgress', '1.3.2'

# RatingBar
pod 'Cosmos', '~> 1.2'

target :LiferayScreensTests do
	pod 'Nocilla'
end

