platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target "LiferayScreens-Showcase-ObjectiveC" do
    pod 'LiferayScreens', :path => '../../..'
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['SWIFT_VERSION'] = '4.0'
		end
	end
end
