source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

pod 'LiferayScreens', :git => 'https://github.com/liferay/liferay-screens', :branch => 'LMW-232-ios-westeros-bank-app'

# the rest of your Podfile