source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'AndorraTelecomPublic' do
  	pod 'LiferayScreens', :path => '../../..'
    pod 'Alamofire'
    pod 'DynamicBlurView'
    pod 'Hokusai'
end
