source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target "WesterosEmployees" do
	pod 'LiferayScreens', :path => '../../../..'

	pod 'TPKeyboardAvoiding'
	pod 'MGSwipeTableCell'
	pod 'PureLayout'
end

